### ISSUE TITLE
Should voters be allowed to change their vote amidst polling? 

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#19]
For snapshot.org, right now any vote that happens can be "edited" during the ballot's opening period.

E.g.  voter could vote "yes" in the beginning and then swing to "no" in the end.

It seems this feature was never implicitly discussed or used since R10. I could be wrong.

Anyhow, what are the effects of voters changing mid vote? Can it be disabled in snapshot pages? Is there a good reason for disabling/leaving it on?

**Comment by idiom-bytes** [comment]
Not available at the moment. 
None one of the hundreds of DAOs have requested this until recently.
https://github.com/snapshot-labs/snapshot/discussions/720

**_1 - I believe the way things are currently implemented, resolve various UX requirements and benefits._** 
**_2 - I do not believe R10 had any significant problem WRT this mechanism, and do not think the data is quantifiable enough to expect this feature._**

I am prioritizing UX vs. some sort of wrench/manipulation/51% attack (which will remain possible regardless of this mechanism). 

We had 30+ proposals to review & cast votes, we can expect a certain amount of error here as well. As we move forward with QV, voting will become slightly more complicated because all options will be inside a single ballot. People may make mistakes, or wish to redistribute their vote count as they vote while read proposals.

Participants are welcomed to vote privately, without disclosing their identities.

I propose this issue is closed for the moment, until UX requirements are well established, and a wide range of voters can engage with the process in a positive manner.

**Comment by TimDaub** [comment]
ok
