### ISSUE TITLE
Round 5 voting mechanic is unsafe

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/oceandao#4]
Current voting mechanism: https://github.com/oceanprotocol/oceandao/wiki/Round-Earmark

I quote the wiki:

> OceanDAO aims to fund 65% of Proposals, up to our Target.

So saying that there are 10 proposals for R5 and the target is 10, too, then OceanDAO wants to fund 6.5 of them.
However, the current vote mechanic where each proposal is put into its own ballet does not exhibit the "safety property" of distributed systems.

The [safety property](https://en.wikipedia.org/wiki/Safety_property) can simply be defined as "something bad/unintended/unexpected will never happen within the system".

If we evaluate the OceanDAO voting mechanism against its assumption that we want to fund between 6-7 projects each round, we can find that it is not guaranteeing safety. To prove it, here's a case where 0 projects are funded in OceanDAO R5:

- Scenario: OceanDAO R5 vote is almost closed. The target of funding 6-7 projects is almost reached. Many users have casted "yes" or "no". But everything went as planned and now there's 6 projects with 51% of "yes". Now let's say that the sum of voting power of all those users is 1M OCEAN.
- An OCEAN whale troll sees this. Using their 2,1M Ocean, 5 minutes before the vote closes, they vote all ballets with a "no". Within a second, all positively voted projects are now negative. They won't get funded.
- Hence, no project is funded for Round 5.

This scenario is violating the safety property as something unintended/bad has happened. Instead of 65% of projects now 0% of projects are funded. Hence, it is reasonable to call the R5 voting process unsafe with regards to the underlying assumptions of the OceanDAO to fund 65% of the target proposals.

Now, you might say: "OK, but that scenario isn't very likely or capital efficient. If a troll whale would do it, wouldn't they harm themselves too?"

I'd argue no, as a similar process as outlined in the above case could be done within a range of a few Ethereum blocks.

As a USD whale, I start acquiring OCEAN now and I constantly check the vote.oceanprotocol.com website until I see the ballots appear. Now, in the block, after the ballots have been snapshotted on, I immediately exit all my OCEANs into another coin.

With the huge sum of OCEAN I have in the snapshot, I downvote all projects. Essentially, I make the round fail.

One could go even further, if say the Ocean troll whale has an economic incentive, then they'd "short" OCEAN right before executing the attack to profit from the turmoil of the vote going wrong.

**Comment by TimDaub** [comment]
"A first-cut solution I can think of is to require all OCEANS to be held in the wallet for a period of at least 30 days to count in the vote snapshot. In this way trolls and speculators will be eliminated from voting, and only longer-term holders who hold through the volatility and have skin in the game would get a vote."

yetti4 on discord

**Comment by TimDaub** [comment]
potentially fitting proposal from vitalik: https://ethresear.ch/t/votes-as-buy-orders-a-new-type-of-hybrid-coin-voting-futarchy/10305

**Comment by idiom-bytes** [comment]
I do not think that issue #4 is a problem because we have an extremely low number of participants who are voting.

I believe you are suggesting modifications to a system that is working across hundreds of DAOs, adds more complexity and surface area that will ultimately lower the signal quality from participants, while increasing friction.

We have [~32,500 holders](https://etherscan.io/token/0x967da4048cD07aB37855c090aAF366e4ce1b9F48), and [less than 100 voters](https://docs.google.com/spreadsheets/d/1e4xb6m-aKcBhwob_p7ereSFneXFPpDjUbSjz13smmHI/edit#gid=1767052349).

More importantly, I believe we should lean heavier on cultural and community-related initiatives to ratify voters towards our [long-term W3SL vision](https://blog.oceanprotocol.com/the-web3-sustainability-loop-b2a4097a36e). 

I will qualify my statement with this:
- Every Ocean holder whether short term or not, is welcomed to vote.
- Every Ocean community is an opportunity, not a threat, for us to engage with, and onboard in our mission towards W3SL.
- Everyone who is currently receiving grants, and building on top o Ocean Protocol should uphold those values.
- We should be working towards onboarding every participant, whether speculator, developer, with 1m tokens or even just a single one.
- We should all be upholding our values, such as what is inside of the CoC. Thank you for pointing me to it, as I want to review it and make sure that EVERY participant is abiding by it in any channel that is supported by OPF or Community.

I am also very much interested in Unnoficial channels and communities, as I believe these are highly-engaged participants who have self-assembled without any need for us to steward the vision behind Ocean. Although they may not operate under the same CoC, I believe our mission remains to engage and onboard them instead of being inflammatory or distant, as this behavior is not constructive towards us being able to focus on higher-order outcomes.

Thank you.
