### ISSUE TITLE
Snapshot Strategy

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/oceandao#46]
### [Deliverable 2 - Snapshot Strategy]
This is an example strategy that is verified by brightID registry: https://snapshot.org/#/strategy/brightid

 A) Create 1 master strategy that encompasses every source we implement (uni2, bancor, etc..) => ocean_master_brightid
 B) Create N BrightId strategies for each source we implement (uni2_brightId, bancor_brightid, ocean_market_brightid)
DOD - Strategy Requirements - Bonus:

 Implement strategy parameter so a multiplier can be passed in, to return a final score.
I.E. Extra 50% votes if registered via BrightID.

**Comment by idiom-bytes** [comment]
@trizin if you are still on this, (and you seem to be keeping up great pace).
Maybe you'll be able to dd this to the strategy.

#### Problem:
- Right now, we may not get a lot of conversions via Bright ID
- Quadratic voting improves working when we get conversions.

#### Towards a solution
- [ ] Add **3Box Ocean Marketplace Registry** as part of the strategy

Do you want to look at this?
- "Adding 3Box support if you are registered in the Ocean Marketplace."
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao-private/333

#### Example DoD:
- [ ] Make it so that the strategy also support looking up your address @ Ocean Marketplace 3box registry.
- [ ] Example Strategy: **sushiswap-multi-did-strategy** <params>: {brightid_registry: str, brightid_multiplier: float, 3box_registry: str, 3box_marketplace_multiplier: float}
