### ISSUE TITLE
Registry Frontend

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/oceandao#47]
### [Deliverable 3- Registry Frontend]
- [x] Deploy registry frontend to facilitate onboarding. Make it easy to register (Anyone can register into brightID to receive bonus votes)

DoD:
- [x] Setup a BrightID registry
- [x] Configure Snapshot + BrightID strategy
- [x] Deploy & validate test w/ BrightID support
- [x] Configure DAOBot to deploy proposals w/ BrightID Strategy
- [x] Deploy Frontend to make it accessible

**Comment by idiom-bytes** [comment]
Perhaps provide support for:
- [ ] Wallet Connect & Metamask
- [ ] Review registry requirements

https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/46

**Comment by idiom-bytes** [comment]
Just a reference from gitcoin. We should be considering the FE so that it can be expanded upon.
Please notice the **% bonus** being communicated based on what you have registered.

![Screenshot from 2021-11-23 08-21-13.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/c33cda9a-6f06-4413-8139-146749d31b6f)
