### ISSUE TITLE
R13 Proposals Submissions - Live-OPS

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#69]
- [x] Review Port for new proposals
- [x] Add proposals to Airtable
- [x] Make sure every project provided all required informations and it's properly registered
 - [x] Check up on projects that do not have sufficient OCEAN.
- [ ] Provide proposal summaries to MarCom for tweets.

**Comment by anapheys** [comment]
@sheriff4 @idiom-bytes @DMats @trentmc @daneklustig 

Items of concern:


End of Round - responsible need to be online for the hour leading up to final deadline in order to: 
provide active support, for example in case DAOBot doesn’t work, etc.
review and log deliverable update submissions (check that they are in and OK; not enough time to review them for quality)
take proposal and give them basic guidance
manually populate air table by deadline
publish on snapshot for due diligence (postpone for 4 days)

Roberto can cover but needs support. Could Daniel help out too? Maybe David?

**Comment by DMats** [comment]
When is the proposal submission deadline for R13?

**Comment by AnaLoznianu** [comment]
@DMats On 04.01.2022, at midnight GMT

**Comment by anapheys** [comment]
Also, as Project Guiding WG Rules get built out making sure if there are hard rules like, "must have n number of comments on proposal to be considered", but if people are submitting at the last minute then this is impossible.
