### ISSUE TITLE
[Parameters & Roadmap WG] What to do with unallocated funds within an earmark?

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/oceandao#75]
**Discord poll:** https://discord.com/channels/612953348487905282/908016760190537798/920225359092408380

**Is your feature request related to a problem? Please describe.**
Status quo (approach 1): if there is 30K earmarked for e.g. "core tech", and only 10K worth of projects competing, the remaining 20K is _burned_. 

**Describe the solution you'd like**
Remaining funds are recycyled. Two variants:

Approach 2: remaining funds are sent to main pot, in that round

Approach 3: remaining funds are not sent to main pot, rather, they are recycled for future rounds (according to result of #49)

Aim of this issue: decide among approach 1, 2 or 3.

**Comment by w1kke** [comment]
I vote for Approach 2 - I think that giving out tokens is a good idea. The community has to take care that they vote out proposals that want to scam or abuse the system.
More projects funded means more experiments which will result in more success. I am optimistic about this process in the long run.

**Comment by tmanthey** [comment]
Growth I believe is the ultimate goal of the OceanDAO. 

- **Reduction**/controlling parameters for the DAO should be the maximum funding per round and the voting process.
- Parameters to be **maximized** are the spending of the set budget and the number number of projects in the DAO.
- Quality should be controlled adapting the funding cap per round to the number of quality projects.
- E.g. if the quality of funded projects is perceived too bad, reduce the funding per round in order to give control to the DAO aka the voting process. I could be part of the parameter wg to align on the funding cap for the next round.

Based on this principles I support proposal 2 and here is why:
- Creating an earmark can be used as making a demand of the DAO visible to the public and gives an incentive to claim a grant within the earmark
- Nevertheless it should not sacrifice the overall goal to maximize the funding of projects within the given funding limits.

**Comment by w1kke** [comment]
@tmanthey - here is the GitHub issue for the discussion around the adoption of the token limit for the next round: https://github.com/oceanprotocol/oceandao/issues/76

**Comment by alexcos20** [comment]
I strongly support approach 3.
Our aim is to grow and incentivize certain areas. We need competition on all earmarks, not just discretionary funds

**Comment by idiom-bytes** [comment]
My systems/game design agrees with @alexcos20 

If all funds are moved from earmarks to a "general" pot, then earmarking is not sufficient in modifying behavior and providing incentives to specific areas.

`Growth I believe is the ultimate goal of the OceanDAO.`
1. Growth needs to be healthy and sustainable. 
2. There are many different verticals that need to gain traction for #1 to be realized.

**Comment by tmanthey** [comment]
> I strongly support approach 3. Our aim is to grow and incentivize certain areas. We need competition on all earmarks, not just discretionary funds

In which way returning/burning unused earmark funds do you think would increase competition between earmarks? The incentive to claim an earmark, which is the increased chance to receive funding, stays the same. I believe the best competition is to have more grant applications than funding.

The only real difference I see is that the budget planning for the overall DAO budget is easier with overspill of unused funds to general as the estimated utilization of earmarks do not have to be put into consideration.

**Comment by tmanthey** [comment]
> **Key Point** >> (Approach 2) All grants available, always reduce to the general earmark. I don't believe this will lead to a behavior change (i.e. too much competition in general -> go build core tech)

It will as soon as there's a squeeze in the general category. In this case claiming the earmarks creates an incentive to increased chances of funding. The main parameters to control competition imo are "funding per round", "number of projects" and the DAO vote itself. Currently the "funding per round" is rather static. I'd rather change that from round to round and simplify all other parameters.

**Comment by kaimeinke** [comment]
I strongly agree with proposal #3 , Approach 3: remaining funds are not sent to main pot, rather, they are recycled for future rounds (according to result of #49)

This allows the pressure to be built up over time and to really make this things happen.

Strong YES from my side.

**Comment by trentmc** [comment]
> [Description] Approach 2: remaining funds are sent to main pot, in that round

> [Q from Scott Milat in Town Hall] Does option 2 mean that if there were $200k tokens not allocated, then those $200k tokens would be split among the grant recipients of that round? Seems excessive?

Answer: no. It is simply added to the main pot, where the usual mechanics take over, just now the total amount available is higher. If a project has proposed for 30K, and they get enough votes to be a winner, they only get 30K, not >30K.

**Comment by MeMent0L** [comment]
Approach #2 is the most appropriate to save funds for good projects and emulate unexpected ecosystem/teams own creations.  It's the simplest solution, and there is a chance that this rule doesn't need to be revised in the future (unlike #3).

Approach #3 works well today with OPF making the calls, but doesn't seem super suited in the context of our desired decentralized governance end-state; i.e. it would require a separate process to rank focus areas and allocate earmarked funds. Other considerations:
 * It doesn't seem right to create n different budgets, independently managed. It's difficult enough with just one IMO 
 * What if priorities/focus areas change over time? 

Net, my preference goes to #2.

**Comment by idiom-bytes** [comment]
> It will as soon as there's a squeeze in the general category.

**This is a reminder that:**
- Earmarking was introduced in Round 4, to curb the fact that 80% (let us assume a pareto distribution) of the funding or more was going into 2 categories: Build Apps + Unleash Data.
- Outreach, Improvements to DAO, and Core Engineering accounted for the remaining 20%.
- The first round earmarked for Outreach caused a BIG turnout.
- The earmark was later switched to "New Participants" which have led to fixing other problems previously, with existing projects taking the whole cake.

I want to tag @brucepon and @trentmc, as I believe this can be one of those circular experiences that without deep knowledge in the area, can lead to problems.

I want to triple down on proposing that only a few group of people are able to sythesize all the history of what has taken place, and think it's pivotal, across all organizations, to entrust this enclave of designers/engineers/analysts/scientists to continue making key decisions.

Please see [how decision making happens at Index Coop](https://docs.google.com/presentation/d/1BK0d_j3crtcRZD2EL2dL0Xon5wOYdORXgPoVw5WexuY/edit#slide=id.gfa1581f4f4_0_1).

> In which way returning/burning unused earmark funds do you think would increase competition between earmarks?

Slight adjustments:
- Burning increase intrinsic collaboration from participants to not let the funds burn (what is happening macro in this group & participants right now).
- Earmarking funds provides guard rails so funds are allocated in constructive ways to support all pillars of the flywheel, including some that are unknown.

> Approach #3 works well today with OPF making the calls.

This approach works well with an experienced team that is looking at data over the long-run to identify improvements in capital allocation & efficiency. Every organization has a team like this. Please see [how decision making happens at Index Coop](https://docs.google.com/presentation/d/1BK0d_j3crtcRZD2EL2dL0Xon5wOYdORXgPoVw5WexuY/edit#slide=id.gfa1581f4f4_0_1).

> But doesn't seem super suited in the context of our desired decentralized governance end-state; it would require a separate process to rank focus areas and allocate earmarked funds.

Decentralization does not mean without structure. It's a giant incentive machine. This group was built around the need to provide a guidelines for growth.

**Comment by MeMent0L** [comment]
Alright, I'll pop by in a few months to check how Index Coop's "Wise Owls" "temporary experiment Group" has been going. 

I'm personally not so bullish on legacy forms of businesses, regardless of whether each department is a DAO or not. 
I believe we ought to design *network governance* rather than *company governance*.

**Comment by tmanthey** [comment]
> * In conclusion, "Free-for-all" has already been tested and did not lead to a squeeze. It led to many undesirable behaviors which is why we now have earmarks.

I think I proposed actually to the DAO in R4 to create an earmark "New Projects", which got implemented until today. The rationale here was that new projects got squeezed as it was hard for them to get votes against established projects.

But I have the impression you are arguing as if the debate was "earmarking vs no earmarking". The intrinsic effect of earmarks is to free certain strategic projects to a certain extend from the squeeze within general projects competition. This effect remains untouched whether **unclaimed** funds of an earmark overflow to general or not. Returning funds also does not create more competitive pressure as it is unknown before the ellections (ex-ante) how many projects will apply for a certain earmarked category. The only effect I see is making the DAO management more difficult as the wg has to consider an estimated earmark utilisation next to intended funding cap.

e.g. 
Option 2: wg want to provide 500k funding total. 60k earmark "core tech". Done
Option 3:wg wants to provide 500k funding total. 60k earmark "core tech". Expected utilisation 0% => Total funding 560k or "real total funding" just 440k?

"Total funding" and "Total amount funded" should ideally be the same amount and are KPI to measure the performance of the DAO. Having earmarks with low utilisation and no overflow would either have the undesired effect of reduce funding for general category or lead to overfunding.

**Comment by idiom-bytes** [comment]
`I'll pop by in a few months to check how Index Coop's Wise Owls temporary experiment Group has been going.`

Couldn't agree more. These are all just really big experiments. However, so is complete decentralization, and we have to remember that to date everything has been done in a centralized fashion with narrow governance.

My [build->measure->iterate] brain weight more towards progressive decentralization.

`This effect remains untouched whether unclaimed funds of an earmark overflow to general or not.`

I've been considering your points Tobias, and I'm leaning towards your outline of enabling funds being moved to the general grants pot.

However, I can't shake off that these might bring us full circle to previous behaviors.
- 500k easily goes towards a general category
- 80% could gets allocated into building apps and unleashing data
- With burning gone, network has no incentive to grow the other pillars to hedge against burn
- We then continue relying on the same efforts to grow and maximize earmark

I believe "Earmarking not going into general" (3) thus serves as a similar effect to burning. Where network participants must collaborate to deploy funding into these other categories, in order to maximize/deploy all available funding.

**Comment by tmanthey** [comment]
> I believe "Earmarking not going into general" (3) thus serves as a similar effect to burning. Where network participants must collaborate to deploy funding into these other categories, in order to maximize/deploy all available funding.

This is a weakspot in the argumentation imo. The network are individual projects scattered across the globe. The main priority of projects is to deliver on grants and/or get a grant. There is absolutely no incentive of individual projects to maximize the total funding of the DAO. Neither there is an interest in distributing the funding across categories.

To maximize/deploy all available funding is a core interest of the wg. So I disagree that burning or unfilled earmarks leads to any kind of network pressure. From what I can see it just leads to wasted resources which is significantly slowing down the growth of the ecosystem.

You can see that actually in the key figures of the DAO. Funding in Oceantoken has dropped by 66% in R10 and R11 compared to R9. Earmark coretech has not been filled with any projects in both rounds. So neither burning nor unfilled earmarks led to increase in funding or distribution but quite the contrary.

**Comment by idiom-bytes** [comment]
Poll on Discord for this topic [can be found here](https://discord.com/channels/612953348487905282/908016760190537798/920225359092408380).

**Comment by trentmc** [comment]
If recycle to treasury, it effectively lowers the budget for the existing round.

I view this as a tradeoff between:
- if recycle to treasury, then it's lower budget for round overall, and a squeeze for teams strongly incentivized to build their own thing; versus
- iif recycle to general, ever-so-slightly stronger incentives for earmarks

**Comment by trentmc** [comment]
The Parameters & Roadmap WG met yesterday to finalize this issue. Discord votes are taken as an input sentiment, not as the final say. The final say is in the WG.

- Discord votes: 6 recycle to general, 8 recycle to treasury

- Discussion: 
  - Alex: problem if not recycle to treasury: won’t incentivize earmarks enough (vote=recycle to treasury)
  - Roberto: “” (vote=recycle to treasury)
  - Robin: lots of people coming in have projects in mind that they want to work on, they wouldn’t switch their opinion. Get more good, incentivized projects into pipeline. And, if earmarks there (vote=recycle to general)
  - Trent: (reflected back Robin’s comments in his )
  - Roberto: changing vote to recycle to general, to maximize # incentivized projects into pipeline
  - Robin: referral system will help even more
  - Trent: (leaning towards recycle to treasury)
  - Alex: (still leaning to recycle to treasury. People will gravitate to lowest friction barrier)
  - Roberto: perhaps do other things to incentivize core tech. Eg larger init value.
  - Robin: we’ve been working on data union for >1 year. It took us a long time to build our own stuff. Now we see we want feature x, and will need to change core tech, only after 1 year.  
  - Roberto: so you’re saying if a team succeeds early on, eventually they’ll go to core tech
  - Robin: yes
  - Trent: If recycle to treasury, then it's lower budget for round overall, and a squeeze for teams strongly incentivized to build their own thing, just to have ever-so-slightly stronger incentives for earmarks.
  - Roberto: The squeeze could be very harsh for teams as we go from 500K OCEAN budget to 200K.
  - Roberto: slight implementation risk to be doable for R13.
  
- **Any objections to “recycle to general”? (none raised)**
- **Decision: recycle to general**

**Comment by trentmc** [comment]
Clarification by Roberto (just for 100% clarity): If [General Category] funding is not fully utilized, remaining funds are recycled to Treasury.

Integration Task: https://github.com/oceanprotocol/DAOBot/issues/95

**Comment by w1kke** [comment]
This is weird - the group decided for recycle to general but now the implementation is recycle to treasury? Will this be changed in the next round (14)? It seems like a contradiction to what we decided in the working group.

**Comment by trentmc** [comment]
@w1kke I think it's fine. There are two steps of recycling here.

1. If funds inside an [x] earmark are not fully utilized, recycle to [General Category] for that funding round. (Decided by this WG in this github issue.)
2. If funds in [General Category] for a funding round are not fully utilized recycle to Treasury for future rounds. (Decided by this WG in github issue [#49](https://github.com/oceanprotocol/oceandao/issues/49))

Alright?

**Comment by w1kke** [comment]
@trentmc but if I look at the implementation in the current round on Ocean Pearl (https://oceanpearl.io/dao-voting - in the top) then I see that this is not happening.
The funds are getting burned/returned to treasury because an earmark is not fully filled instead of going back to the general category. This means that projects will not get funded in this round.
I am just trying to understand whether I am misunderstanding something or the system has a flaw right now - it would be important to catch this now so that projects can get the funding if it is available.

Quote from the Ocean Pearl Discord:

Maka | Ocean Pearl — Today at 11:49 AM
Hello @Robin (alpha.DataUnion.app) , 
this round we are having a smaller grantpool overall, so not all proposals will receive a funding, even if all proposals would have been upvoted.
In addition to that, the overall pool is also split into a "general" pool and separate "earmark" pools that are only eligible for marked proposals.
For your example, the proposal is only eligible for the "general" pool, which is depleted, it needs 253 votes to get ahead of the proposal with the lowest effective votes, that still got funding from the "general" pool.
The burned tokens are from an earmarked pool. 
Maka | Ocean Pearl — Today at 12:07 PM
I hope this cleared things up a little

**Comment by trentmc** [comment]
Looks like a bug then.

I just created an issue for this: #119

And you're right - it's important to catch this now so that projects can get the funding if it is available.
