### ISSUE TITLE
[OceanDAO][WG][Scaffolding] Deploy Coordinape + Provide support for funding distribution

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#83]
Funding Distribution:
- This is executed via a voting epoch. Where all circle participants give scores to each other. At the end of the epoch, the total GIVE amount is provided for each EOA. Then funds are distributed to each EOA based on amount of GIVE.
- All wallets for this circle will be onboarded as Polygon or xDAI (Coordinape dependant) and we may need technical support to properly distribute these funds (automatically & at scale)

#### DOD:
- [x] Deploy a coordinape circle for Project-Guiding Working Group
- [x] Configure + initiatilize circle to onboard initial participants and enable participants to bring on additional members as part of the PGWG
- [x] Execute first funding epoch
- [ ] Provide support as needed to facilitate funding distribution.
- [x] Write out tasks to improve overall process. (1) automate funding process (2) improve proposal review & guidance process (3) improve onboarding members to the WG.

**Comment by drprk** [comment]
Here's the recommended logistic for Payment Streams:

**Superfluid demo:**

https://recondite-magnesium-e3c.notion.site/Testing-Superfluid-on-Polygon-testnet-8dd74cc7e3ae47658870662a993929a3

**Explainer:**

- Testing payment on a 4-weekly epoch through Polygon network
- Superfluid deposits setup with Test tokens of USDC, DAIx & Matic for txns

- Assume payment streams of 50$ per week to Account A

0x61Ec1216Afe91Be1a087f9e8C26F913091FA9934

- Assume payment stream of 100$ per week to Account B

0x254Ba7254366CA7afE007897358Ee0b45CA933E2

- Once payment stream is enabled seamlessly -> Steps can be repeated for multiple accounts as applicable.

**Note:**

- I believe payment streams are cyclical and viewed per second

![image](https://user-images.githubusercontent.com/88657058/146497351-37f1c82c-f22f-4824-9dae-7e85ea67e72f.png)

- Due to the bottleneck behind cyclical streaming payments, you can choose to do one-off payments

![image](https://user-images.githubusercontent.com/88657058/146497528-865cf544-dea5-4f4f-97de-6e2ef32cb740.png)

**Comment by drprk** [comment]
**Deploy a coordinape circle for Project-Guiding Working Group**

For this purpose, we could explore forums where there's a comfortable project review history for each groups?

- **Reddit**

Private reddit groups might be useful unless we don't prefer that as a collective discussion forum

- **Notion**

Notion sites might be good to have with a great UI to surf through Project Groups

_Drawback_: Single point of failure with the page-owner, lack of voting mechanism (apart from embedded bots)

Example: https://drjohndoe.notion.site/Project-Co-ordinape-bf331c9335cd47b1aad5266bd48e043f

- **Discourse**

Discourse might be more popular to explore given the popular usage with adequate integrations.

https://www.discourse.org/

- **BIP.so**

A beta-ish site, that's more suitable with Discord integrations with visibility on emote-reacts to specific lines/comments, which can be made use of for discussion points and as voting proxies.


Example: 

https://bip.so/@questbook/How-to-use-Discord-nYjKh

![image](https://user-images.githubusercontent.com/88657058/146509581-a427ab15-67b6-41b5-9cae-2eb811681953.png)

Drawback: Quite less intuitive compared to other forums, The onus is on the admin of the Discord group to make the process conducive to happen. From a users perspective, however it is slightly easier to on-board straight from discord.

**Comment by idiom-bytes** [comment]
Hi Prakash, thanks for providing your feedback, digging into superfluid, running some tests, and even recording a video to show how it works, that's awesome.

Having said that, I'm wondering:
1. Why you believe Superfluid would be useful in conjunction with Coordinape?
2. How you think we should balance: using existing tech  that may feel constraining/limiting (Discord | Port) vs. adding new which may create fragmentation ( reddit | BIP).

**Comment by idiom-bytes** [comment]
#### WG Scaffolding Outline
Here is an outline of what I refer to as scaffolding for the WGs. 
https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/oceanprotocol/oceandao/40

When it comes to payment, I had proposed 2 main stream of income for WGs or as you put it "sub-daos", with each funding stream addressing a particular role:
1. Coordinape. Serves as a social/subjective layer where participants GIVE to each other, and funding is paid in a retroactive manner for their contributions.
2. Sourcecred. Serves as a mechanical/objective layer, where participants are rewarded based on their contributions towards completing tasks & deploying measurable outcomes.

#### WRT Coordinape & Superfluid
As far as I can tell, Coordinape enables participants to execute a voting epoch where everyone assigns GIVE to each other based on their contributions and impact to the WG. The payments should then be executed at the end of the Epoch, based on the amount of GIVE each participant received.
1. This means that the payment amount for each participant changes with every epoch.
2. The epoch would be conducted at the end of each round, meaning that participants have already delivered the work at this point and the funding, thus represents their retroactive contributions and impact into the community. < I'm wondering how Superfluid would help under this scenario.

**Comment by idiom-bytes** [comment]
This comment is assuming a "final form" of the WG, where every process/tool is implemented and this WG is functioning. Here is an example for how I can see the tools, steps, and budget associated with each funding stream being executed based on my limited knowledge.

Initially, I am proposing simply using Coordinape to address the needs of the whole WG.
If Coordinape funding does not provide an appropriate distribution, then specific payments could be done retroactively to fund specific outcomes (like paying a WG lead / core contributor).

#### Overview
Funding for the PGWG may be split into different streams, each one aimed at solving a particular problem. 

Stream #1 - Coordinape (every member in WG) - 30%
This funding stream serves to support social-dynamics & understanding how the WG is self-organizing.

Stream #2 - Sourcred (every member in WG) - 30%
This funding stream serves to support key-deliverables & provides funding towards objective outcomes that need to be implemented by the WG.

Stream #3 - Superfluid (core contributors to WG) - 40%
This funding stream serves to support key-contributors & provide them with base-funding for their continuous work.

Coordinape:
1. Coordinape epoch is executed at the end of each funding round
2. Participants GIVE to each other, yielding a final distribution of GIVE among all participants
3. Final distribution of GIVE would then be equal to how funds should be distributed towards WG contributors
4. Funding would be executed via a polygon distributor by simply paying out to every wallet, based on the GIVE received.

Sourcecred:
1. Tasks would be continuously generated, completed, iterated & tracked via sourcred
2. Sourcred [automatically calculates how Cred](https://sourcecred.io/docs/beta/cred/) is earned by members
3. [Grain amounts are then calculated and distributed](https://sourcecred.io/docs/beta/grain) to Cred contributors

Superfluid:
1. Some key members who are continuously contributing to the WG need to be retained
2. These members would have a predefined amount to receive per OceanDAO funding round so they can continue to lead the group & provide support by supporting meetings, creating & supporting issues towards Sourcecred & Coordinape circle. 
3. Superfluid would then be used to stream continuous payment to these members, in order for them to maintain engagement & delivery of responsibilities within the group

**Comment by drprk** [comment]
Hello Roberto, thanks for the feedback

Re: **Why you believe Superfluid would be useful in conjunction with Coordinape?**

I believe you wanted to have an option of automating the process of funding epochs, hence I thought it would be worthwhile considering it. If there are other mechanisms that are already in place, perhaps You/Ocean core could have a better idea of options that you feel are a little better.

Superfluid with its one-off/payment stream track can be useful to consider in adjunction to Coordinape + v0.1 processes.

Re: **How you think we should balance: using existing tech that may feel constraining/limiting (Discord | Port) vs. adding new which may create fragmentation ( reddit | BIP).**

I believe these could be just options to look into at any point of time. In hindsight after looking at the other discussions, it is a little premature to fragment the current process for V0.1. I believe we could just re-adjust the admin interactions on Port to achieve our goals

-----------------------------------------

Thanks for mentioning the Zenhub example for scaffolding. I wasn't aware of this context, will have to look at it a little closer.

Agree with rest of the content on https://github.com/oceanprotocol/oceandao/issues/83#issuecomment-997300613 

> WRT Coordinape & Superfluid:

So one-off payments can probably be the process in case we are using Superfluid here. IF you are comfortable with that, Superfluid can still be relevant given the fact that we still need a manual component of deciding the Splits prior to the GIVE proportions.

----

https://github.com/oceanprotocol/oceandao/issues/83#issuecomment-997302484

- The proposed format looks good, we could use a little more explanation to folks who are not familiar with Sourcecred yet. I'm a big fan of the product, I'm yet to see them in action and we could use some DD in breaking it down for the onboarded members of the WG. Once we finalize the process, we could use with a Medium post of how Sourcecred tasks works for Coordinape<-> PG-WG

- The Superfluid concept of payment streams makes sense here, since we would need a perpetual mechanism for PG leaders (Applicable for both early contributors + future regulars of PG-WG).
