### ISSUE TITLE
[Parameters & Roadmap WG] Earmark to increase gender diversity?

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/oceandao#84]
**Is your feature request related to a problem? Please describe.**

[@Shamburgularara on Discord](https://discord.com/channels/612953348487905282/908016760190537798/920723875019518022)
Hi all, I wanted to suggest an item in this group should be to increase gender diversity of the DAO and people applying to grants. Not 100% sure if this is the right WG for this, but I feel it needs to be somewhere. This is a very male dominated DAO, which is intimidating for many women. 

**Describe the solution you'd like**
Many ideas were discussed. The idea in _this_ issue is to have an earmark for gender diversity. Details below.

Q: should there be an earmark to increase gender diversity? If yes, what should it look like? How much?

**Comment by trentmc** [comment]
Thread on discord that kicked this off is below. Starting with [this message](https://discord.com/channels/612953348487905282/908016760190537798/920983171787530291).

----

Shamburgularara — Dec 16 at 6:07 PM
Hi all, I wanted to suggest an item in this group should be to increase gender diversity of the DAO and people applying to grants. Not 100% sure if this is the right WG for this, but I feel it needs to be somewhere. This is a very male dominated DAO, which is intimidating for many women. An outreach programme to the likes of Surge or Meta Gamma Delta communities, to make women more aware of the grants here and application criteria, would be a really great start

----
Idiom | Ocean — Yesterday at 6:13 PM
Hi @Shamburgularara this is a great recommendation and I would love to support this initiative!
I agree that we should be increasing diversity and being as inclusive as possible!

Would you or someone you know be interested/available to execute on this outreach?

----
Shamburgularara — Yesterday at 6:20 PM
Thanks very much. I am more than happy to, yes. and I'm sure my cofounder @xandra would like to too (she's also involved in other female focused DAOs). I would like to point out though that gender diversity benefits everyone, yet it often falls on women  to execute these tasks. So ideally we'll have more than just women actively executing on this

----
Tobias Manthey — Yesterday at 6:20 PM
Awesome looks coherent to me

----
Idiom | Ocean — Yesterday at 6:33 PM
As a bird, I am in full support of increasing diversity so everyone feels welcomed, heard, and supported!

I would love to welcome you and @xandra to:
1. Write a proposal: https://github.com/oceanprotocol/oceandao/wiki/Grant-Proposal-Template
2. Submit it to Port: https://port.oceanprotocol.com/c/oceandao/round-13/73
3. Reach out to the project-guiding WG for support: https://discord.com/channels/612953348487905282/908016658239610920

Please let me know what I can do to make sure this initiative takes place and receives support from the DAO.
🙌 🌍 🏳️‍🌈 ♥️ (no gender flag, so rainbow is the best I could find!)

----
trentmc0 — Today at 8:37 AM
This is a great point! I like the discussion that has followed as well.

A complementary idea: this WG could create an earmark for teams with >=1 females. Low-ish implementation effort, but could make a difference. Would love to know your thoughts.

----
Robin (alpha.DataUnion.app) — Today at 9:14 AM
I think this is the quickest way to implement this. But maybe instead of >= 1 females >50% females in the team?
We have a lot of team members and two of them are woman, so we would already qualify while that is just around 20% of the team.

----
trentmc0 — Today at 9:17 AM
Good points. Let's explore. What if simply >=1  female founder?

----
xandra — Today at 10:07 AM
@trentmc0 & @Robin (alpha.DataUnion.app) - great points, thanks for your input! I think >=1 female founder OR 50% female team? I think it’s good to have visibility over who is in teams. I think anon is a good thing, but it hides the gender imbalance in the space.
We have a few communities we are a part of that we would love to advertise this initiative to

----
Shamburgularara — Today at 10:10 AM
Yes I like this cos my worry is women feel/are used as a token woman. It’s good to have this mix of founder or team - I think it helps that potential issue a bit, and also makes the criteria more flexible which will increase the teams applying

----
trentmc0 — Today at 11:13 AM
Thanks, this is great👍

I think it's at the point where we can get a github issue to "ratify" this proposal, for any further discussion, take to a discord poll, and finalize. If you like, I can handle it. Lmk.

**Comment by trentmc** [comment]
To summarize the above comments, the current proposal is:

Have a "Gender Diversity" Earmark. A team is eligible if >=1 female founders or >= 50% female team.

**Comment by XandraMcC** [comment]
Additions to yesterdays discussion:

Gyan0890 — Today at 2:23 PM
It's really exciting to see more and more protocols stepping up to create an inclusive ecosystem. This is one of the things I personally love about web3 <3. A bit about myself and some of my observations being in the crypto industry for about 5+ years now 🙂
1. I started my journey into the crypto space as a freelance Solidity dev and am currently working with various projects as an architect, developer, content creator and CTO. My main interest in at the intersection of diversity and inclusion, education and blockchain.
2. I kickstarted the WomenWhoCode Blockchain community(womenwhocode.com/blockchain) in 2019, in order to get more women devs in the blockchain space. I continue to work with other communities to get more women in this space now. Some learnings from my experience:
- More and more women are looking to switch to the web3 space because of the transparency, opportunities and flexibility offered by the jobs in the space. 
- There is a lot of apprehension on "where and how to" start.
- Specifically targeted bounties/incentives for women(in hackathons/other events) has shown significant rise in female participation in these events/hackathons.
- Having mentors supporting women through their learning journey(both technical and non-technical) can be quite helpful to push them in the right direction.

xandra — Today at 3:04 PM
Also, @dataqueen is the founder of HER Dao, and we thought it would be great to do a collaboration between Ocean x HER to really make this initiative wide reaching. We have many women interested already! @greenBee would be keen to lead this initiative

**Comment by Aleborda21** [comment]
I think this is an awesome initiative!!
Some thoughts 
1. Gather some women or other people from Ocean and learn what are some of the skillsets or interests that are currently useful in Ocean as well as gaps that need to be filled --> we can then turn this into some kind of an easy onboarding guide where women can check if a) they resonate with Ocean's mission and b) Have an easy path to follow to understand how their own skills are transferrable to work done here at Ocean
2. Increase women's awareness of Ocean grants hence those working in some cool projects can apply or join a team 
3. Host slightly more technical workshops or even small hackathon like projects related to Ocean and web3 hosted by some of the awesome members here like @greenBee or even in collab with @gyan0890 and WomenWhoCode blockchain
4. Share these initiatives or those we choose to move forward to with communities we are part of like HER and Surge

Let me know what you think! + was there a call/chat soon to organize?

**Comment by trentmc** [comment]
Thanks everyone for all the excellent discussion here, in the discord chat, and in other meetings and chats. There are many great ideas towards ensuring a level playing field, and encouraging diversity. Notably, there's an R13 grant proposal for diversity outreach/etc, [here](https://port.oceanprotocol.com/t/the-phoenix-guild/1279) :) The WG discussed and arrived at: given that grant proposal, the other ideas, and that earmarks are more towards specific outcomes, the earmark idea (this issue) will not be pursued at this point.
